IF (MINGW)
    message(STATUS "Uninstalling in MINGW")
    exec_program(${CMAKE_COMMAND} ARGS "-E remove_directory ${PROJECT_SOURCE_DIR}/dist/nimuh-${nimuh_VERSION}/")
ELSE()
    message(STATUS "Uninstalling in Linux")
    exec_program(${CMAKE_COMMAND} ARGS "-E remove ${CMAKE_INSTALL_PREFIX}/bin/nimuh")
    exec_program(${CMAKE_COMMAND} ARGS "-E remove ${CMAKE_INSTALL_PREFIX}/share/applications/nimuh.desktop")
    exec_program(${CMAKE_COMMAND} ARGS "-E remove_directory ${CMAKE_INSTALL_PREFIX}/share/nimuh/")
ENDIF (MINGW)
